#ifndef STRINGTABLE_H
#define STRINGTABLE_H

#include <QtWidgets>
#include <QObject>

class StringTable : public QObject
{
    Q_OBJECT
public:
    explicit StringTable(QObject *parent = 0);


#define Str_Warning tr("Warning")
#define Str_Please_input_machine_name tr("Please, input server name.")
#define Str_Please_input_monitoring_area_name tr("Please, input monitoring area name.")
#define Str_Duplicated_machine_name tr("Duplicated server name.")
#define Str_Duplicated_server tr("Duplicated server ip adress.")
#define Str_Duplicated_ip_adress tr("Duplicated ip adress.")
#define Str_Duplicated_monitoring_area_name tr("Duplicated monitoring area name.")
#define Str_Invalid_ip_address tr("Invalid IP adress.")
#define Str_Please_input_user_name tr("Please, input user name.")
#define Str_Please_input_port_num tr("Please, input port num.")
#define Str_Please_input_password tr("Please, input password.")
#define Str_Please_input_port tr("Please, input port.")
#define Str_Machine_Name tr("Machine Name")
#define Str_IP_Address tr("IP Address")
#define Str_Chanel_Count tr("Chanel Count")
#define Str_Machine_Type tr("Server Type")
#define Str_Status tr("Status")
#define Str_Disconnected tr("Disconnected")
#define Str_Connected tr("Connected")
#define Str_Question tr("Question")
#define Str_Are_you_sure_to_delete_selected_machine tr("Are you sure to delete selected server?")
#define Str_Are_you_sure_to_delete_selected_black_person_infos tr("Are you sure to delete selected black person infos?")
#define Str_Are_you_sure_to_delete_selected_monitoring_area tr("Are you sure to delete selected monitoring area?")
#define Str_Are_you_sure_to_delete_selected_face tr("Are you sure to delete selected face?")
#define Str_Server tr("Server")
#define Str_IP_Camera tr("IP Camera")
#define Str_Chanel tr("Chanel")
#define Str_Save_File tr("Save File")
#define Str_Please_add_a_face tr("Please, add a face.")
#define Str_Please_input_a_name tr("Please, input a name.")
#define Str_Please_select_target_camera tr("Please, select target camera.")
#define Str_Name tr("Name")
#define Str_Gender tr("Gender")
#define Str_Birthday tr("Birthday")
#define Str_Address tr("Address")
#define Str_Description tr("Description")
#define Str_Male tr("Male")
#define Str_Female tr("Female")
#define Str_Open_File tr("Open File")
#define Str_Open_Folder tr("Open Folder")
#define Str_Similiarity tr("Similiarity")
#define Str_Captured tr("Captured")
#define Str_Black_DB tr("Black List")
#define Str_LOG_UID tr("LOG UID")
#define Str_Time tr("Time")
#define Str_Search tr("Search")
#define Str_Stop tr("Stop")
#define Str_Please_select_chanel tr("Please, select chanel.")
#define Str_Monitoring tr("Monitoring")
#define Str_Machines tr("Machines")
#define Str_Setting tr("Setting")
#define Str_Add  tr("Add")
#define Str_Edit tr("Edit")
#define Str_Delete tr("Delete")
#define Str_Chanel_Setting tr("Chanel Setting")
#define Str_Monitoring_Area tr("Monitoring Area")
#define Str_Single_Camera_Display tr("Single camera display")
#define Str_Quad_camera_display tr("Quad camera display")
#define Str_3_3_camera_display tr("3 * 3 camera display")
#define Str_4_4_camera_display tr("4 * 4  camera display")
#define Str_Add_from_file tr("Add from file")
#define Str_Add_from_batch tr("Add from batch")
#define Str_Surveillance_Setting tr("Surveillance Setting")
#define Str_Camera_Setting tr("Camera Setting")
#define Str_Search_Log tr("Search Log")
#define Str_Search_Black tr("Search Black")
#define Str_Date_Time tr("Date Time")
#define Str_Start_Time tr("Start Time:")
#define Str_End_Time tr("End Time:")
#define Str_Face tr("Face")
#define Str_Set_Face tr("Set Face")
#define Str_Threshold tr("Threshold:")

#define Str_Captured_Image tr("Captured Image")
#define Str_Face_Detection tr("Face Detection")
#define Str_Enrolled_Face tr("Enrolled Face")
#define Str_Name_ tr("Name:")
#define Str_Gender_ tr("Gender:")
#define Str_Birthday_ tr("Birthday:")
#define Str_Address_ tr("Address:")
#define Str_Description_ tr("Description:")
#define Str__Down tr("Down")
#define Str__Up tr("Up")
#define Str_Ok tr("Ok")
#define Str_Cancel tr("Cancel")
#define Str_Monitoring_Area_Name_ tr("Monitoring Area Name:")

#define Str_Add_Files tr("Add Files")
#define Str_Add_Folder tr("Add Folder")
#define Str_Process tr("Process")

#define Str_Add_Face tr("Add Face")
#define Str_Delete_Face tr("Delete Face")

#define Str_IP_Address_ tr("IP Address:")
#define Str_Port_Num_ tr("Port Num:")
#define Str_User_Name tr("User Name:")
#define Str_Password_ tr("Password:")
#define Str_Min_Face_Size tr("Min Face Size")
#define Str_Threshold tr("Threshold")
#define Str_BlackCandidateCount tr("Rank")
#define Str_Apply tr("Apply")

#define Str_Info tr("Info")
#define Str_Manage tr("Manage")
#define Str_Full_Image tr("Full Image")
#define Str_Add_to_black_list tr("Add to black list")
#define Str_Export_image tr("Export image")
#define Str_Machine_Name_ tr("Machine Name:")

#define Str_Add_Black_List tr("Add Black List")
#define Str_Select_Monitoring_Area tr("Select Monitoring Area")
#define Str_Enroll_Batch tr("Enroll Batch")
#define Str_Edit_Black_List tr("Edit Black List")
#define Str_Log_Detail tr("Log Detail")
#define Str_Machine tr("Machine")
#define Str_VMSClient tr("VMSClient")
#define Str_Select_Image tr("Select Image")
#define Str_About tr("About")

#define Str_Score tr("Score")
#define Str_Clear tr("Clear")
#define Str_Are_you_sure_to_delete_all_info tr("Are you sure to delete all infos?")

#define Str_Export tr("Export")
#define Str_Import tr("Import")
#define Str_Send_to tr("Send to")
#define Str_Unkown_format tr("Unkown format!")
#define Str_Select_chanel tr("Select chanel")
#define Str_Group tr("Group")
#define Str_Black tr("Black")
#define Str_White tr("White")

#define Str_Password tr("Password")
#define Str_New_assword tr("New Password")
#define Str_New_assword_ tr("New Password:")
#define Str_Confirm_Password_ tr("Confirm Password:")
#define Str_Change_Password tr("Change Password")
#define Str_Old_Password_ tr("Old Password:")
#define Str_Remove_Password tr("Remove Password")
#define Str_Fail_to_match_old_password tr("Fail to match old password.")
#define Str_The_passwords_you_typed_do_not_match tr("The passwords you typed do not match. Please retype the new password in both boxes.")
#define Str_Fail_to_match_password tr("Fail to match password.")
#define Str_Please_input_a_new_password tr("Please, input a new password.")
#define Str_Please_input_a_confirm_password tr("Please, input a confirm password.")
#define Str_Log_In tr("Log In")
#define Str_Alarm tr("Alarm")
#define Str_Close tr("Close")
#define Str_Capture tr("Capture")

#define Str_VideoSource tr("VideoSource")
#define Str_Refresh tr("Refresh")
#define Str_Preview tr("Preview")
#define Str_Select_Camera tr("Select Camera")

};

#endif // STRINGTABLE_H
